### ISSUE TITLE
两个使用部署问题

### ISSUE THREAD

**Issue by larrykoo711** [daivem/RedisMyAdmin#13]
1. 对于有auth的RedisServer怎么配置，配置文件没有描述呢？
2. 是否支持读取序列化的数据正常显示，而不是乱码?

@hitian

**Comment by daivem** [comment]
1、暂时未支持，短期内将会支持上。
2、暂无计划

**Comment by larrykoo711** [comment]
@daivem 好吧，还有一个问题，我明明安装了phpredis的扩展，还是提示我下面这个信息我安装

**Comment by daivem** [comment]
请查看phpinfo中，是否有redis那个扩展。

**Comment by daivem** [comment]
0.3.6已支持redis的auth
