### ISSUE TITLE
部署成功，看不到string类型的value

### ISSUE THREAD

**Issue by hao0111** [daivem/RedisMyAdmin#18]
你好，在linux环境下，通过nginx部署成功后，keys能正常展示，但是对应string类型的value却显示空白（类型编码为raw 和 embStr），通过admin手动新增的string类型可以显示！请问是否还缺失包？

**Comment by daivem** [comment]
在显示value的时候，会执行format_html($values) 对html标签进行转换

`
helpers/common_helper.php line 103
function format_html($str) {
           return htmlentities($str, ENT_COMPAT, 'UTF-8');
    }
`

有可能是这里的转换结果为空导致。之前偶尔遇到过一些特殊字符会出现这样的情况。不知可否告知几个会显示空白的value，方便重现？

**Comment by daivem** [comment]
新版修改了转换函数，虽然是有部分是乱码，但其它正常字符可以正常。
