### ISSUE TITLE
导出 list 报错

### ISSUE THREAD

**Issue by xiewenlong** [daivem/RedisMyAdmin#19]
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>

<p>Message:  Redis::lGet() expects exactly 2 parameters, 1 given</p>

<p>Filename: controllers/export.php</p>

<p>Line Number: 132</p>

</div>RPUSH "test_list" ""

**Comment by daivem** [comment]
感谢，问题已经发现，将在下个版本中修复

**Comment by daivem** [comment]
0.4.2.1已修正
