### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by iuphero** [daivem/RedisMyAdmin#7]
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

改为

```
 $_config[0] = &$config;                                        
 return $_config[0]; 
```

**Comment by daivem** [comment]
请问使用的PHP版本是多少？

**Comment by iuphero** [comment]
是5.6.8

在 2015-06-07 23:41:50，"daivem" notifications@github.com 写道：

请问使用的PHP版本是多少？

**Comment by daivem** [comment]
已修正，并已merge到master
